//
//  ContentView.swift
//  WinZoom
//
//  Created by Dylan Batt on 07/03/2026.
//
//  This file is intentionally empty.
//
//  WinZoom is a menu bar-only (LSUIElement) application — it has no main
//  window and no Dock icon.  The default ContentView generated by the Xcode
//  App template is retained here as a placeholder to avoid breaking the
//  project structure, but it is never instantiated at runtime.
//
//  How the UI is presented instead
//  ────────────────────────────────
//  • Settings panel  → SettingsView, opened by MenuBarManager via the
//                      "Settings…" menu item.
//  • About panel     → AboutView, opened by MenuBarManager via the
//                      "About WinZoom" menu item.
//  • Status banner   → PermissionsView, embedded inside SettingsView.
//
